---
interfaces:
  - name: Management1
    mode: l3
    ip_address: 192.168.1.42/24

  - name: Loopback0
    mode: l3
    ip_address: 10.1.1.1/32

  - name: Ethernet1
    mode: l3
    ip_address: 192.168.13.1/24

  - name: Ethernet2
    mode: l2
    vlan: 100

  - name: Vxlan1
    source_interface: Loopback0
    vlan: 100
    vni: 90100
    vtep: 10.2.2.2

routers:
  - name: ospf 1
    networks:
      - network: 10.1.1.1/32
        area: 0.0.0.0
      - network: 192.168.13.0/24
        area: 0.0.0.0
