---
interfaces:
  - name: Management1
    mode: l3
    ip_address: 192.168.0.1/24

  - name: Loopback0
    mode: l3
    ip_address: 10.1.1.1/32

  - name: Ethernet1
    mode: l3
    ip_address: 192.168.11.1/24

  - name: Ethernet2
    mode: l3
    ip_address: 192.168.21.1/24

routers:
  - name: ospf 1
    networks:
      - network: 10.1.1.1/32
        area: 0.0.0.0
      - network: 192.168.11.0/24
        area: 0.0.0.0
      - network: 192.168.21.0/24
        area: 0.0.0.0
